name: Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write        # nécessaire pour créer une Release
  packages: write        # nécessaire pour push sur GHCR
  actions: read

defaults:
  run:
    shell: bash          # évite les "bad substitution" en /bin/sh

env:
  BUILDKIT_PROGRESS: plain

jobs:
  quality-security:
    name: Code quality & Security scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trivy (filesystem)
        uses: aquasecurity/trivy-action@0.33.0
        with:
          scan-type: fs
          scan-ref: .

  docker-release:
    name: Build & Release Docker
    runs-on: ubuntu-latest
    needs: [quality-security]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Buildx setup
        uses: docker/setup-buildx-action@v3

      - name: Set IMAGE_NAME (lowercase)
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (and push on non-PR)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trivy (image) - only on non-PR
        if: github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@0.33.0
        with:
          scan-type: image
          image-ref: ${{ env.IMAGE_NAME }}:latest

      - name: Create GitHub Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Release v${{ github.run_number }}"
          body: |
            generated github release
            - Docker image: ${{ env.IMAGE_NAME }}:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}